### ISSUE TITLE
Add logo to providers

### ISSUE THREAD

**Issue by nichtich** [gbv/login-server#10]
Providers should be configurable with a logo (see [this example](https://github.com/MichalSzorad/react-social-login-buttons#react-social-login-buttons))

**Comment by stefandesu** [comment]
I think we need to create custom buttons for this because ORCID and Mediawiki are not included in any of those social login bundles.

For GitHub, we can use the [mark](https://github.com/logos).
For ORCID, we can use the [green iD logo](https://figshare.com/articles/ORCID_iD_icon_graphics/5008697).
For Mediawiki, we could use the [Wikimedia Community Logo](https://meta.wikimedia.org/wiki/Wikimedia_Community_Logo).

We could add an option to provide a URL to an imagine file in the providers configuration. Alternatively, we could add a static file folder where these images can be placed with the provider ID as the name.

**Comment by nichtich** [comment]
Yes and VZG LDAP would get the [VZG logo](https://www.hbz-nrw.de/projekte/LASeR/logo-der-vzg/view).

**Comment by stefandesu** [comment]
Logos are now implemented. I'd make it all a bit nicer looking though, it's just a first quick implementation.

**Comment by nichtich** [comment]
General nicer layout is part of #14, so closing this
