### ISSUE TITLE
Show list of open websocket connections and/or tokens?

### ISSUE THREAD

**Issue by nichtich** [gbv/login-server#13]
Just for curiosity - is it possible to get a list of open web-sockets for the current user, so the user can find out where he/she his login server account is currently used? Or the number or currently valid tokens?

**Comment by stefandesu** [comment]
A list of open WebSockets and a list of open cookie sessions would be no problem. We could even add an option to close those sockets/sessions.

A list of valid tokens is currently not possible because we don't keep a record of created tokens. But due to the short-lived nature of those tokens, I don't think it would be necessary.
