### ISSUE TITLE
Remove duplicated requests from websocket API

### ISSUE THREAD

**Issue by nichtich** [gbv/login-server#20]
I prefer less code and less alternatives to increase maintainability and reduce complexity. Right now the following HTTP API requests can also be performed via WebSocket API: 

* GET /publicKey
* GET /providers
* GET /token

and the following can not be performed via HTTP API requests:

* GET /users (with optional URI query parameter)
* GET /currentUser (not required but for consistency)
* GET /user/:id
* PATCH user

Adding the missing methods to WebSocket adds complexity, especially because different kinds of request parameters exist). Better functionality from WebSocket so there is only one dedicated way for each task. The WebSocket API should be for events and the HTTP API for requests.

**Comment by stefandesu** [comment]
True. But my reasoning was that the client will likely have an open WebSocket connection anyway, and performing those requests via the WebSocket would save some overhead.

The added complexity for the existing WebSocket requests is minimal (just a few lines of code total), but you're right that adding the other requests would add a little more complexity (mainly because we'd need to restructure the requests itself (separate handling the request from handling the route etc.).

If you want I can remove the WebSocket requests and adjust [login-client](https://github.com/gbv/login-client) accordingly before we integrate the whole thing in Cocoda.

**Comment by stefandesu** [comment]
I just had another idea:

We could remove the requests from the WebSocket API, but keep the event types and send `publicKey` (or `about` like the endpoint) and `providers` right after connecting to the WebSocket. The client needs those anyway, so this would reduce the number of HTTP requests by two and we wouldn't need to adjust login-client. 

What do you say, @nichtich?

**Comment by nichtich** [comment]
Yes, so the WebSocket only sends events (one-way) and the HTTP API is for explicit requests.

**Comment by stefandesu** [comment]
The only request that can be sent via WebSocket is now `authenticate`. It is still to be determined if this is actually necessary, but at least one browser (Brave) has a bug where cookies are not sent with WebSocket requests, so I'd leave this in for now. All other requests were removed and the WebSocket now proactively sends `about` and `providers` events after a connection has been established. [login-client](https://github.com/gbv/login-client) was already adjusted accordingly.
