### ISSUE TITLE
Allow to configure cookie.maxAge

### ISSUE THREAD

**Issue by nichtich** [gbv/login-server#24]
And expose the value via `/about`. A reasonable value is given in days instead of seconds. Document that a user is automatically logged out after the maxAge value (this is the effect of deleting the session cookie, isn't it?). Open question: use `roling` (maxAge after last use) or not (maxAge after session initiation).

**Comment by stefandesu** [comment]
I think it would be totally unreasonable to log a user out when they've been actively using the account, so I'd vote for using `rolling` (that's how I implemented it now).

One open question though: If a user is using their account only through a client (e.g. Cocoda), their session won't be refreshed regularly and therefore they would be logged out after 30 days. Is this okay (I tend toward no)? We could fix it by regularly refreshing the session through `login-client`, or implement a mechanism to refresh the session server-side using the WebSocket activity (because each WebSocket is associated to a session).

**Comment by nichtich** [comment]
If a user restarts its browser, the session cookie is deleted anyway. Having to log every few month sounds reasonable to me and I think this is how other web applications do it as well. Moreover the user may still be  logged in by its identity provider so he/she is directly send back to the application.
