### ISSUE TITLE
Reduce user data for each identity

### ISSUE THREAD

**Issue by nichtich** [gbv/login-server#34]
* omit fields with `null` value, e.g. ORCID has `"username": null`
* what is identity field `id` required for? Do we need both, `id` and `username`?

**Comment by stefandesu** [comment]
> * what is identity field `id` required for? Do we need both, `id` and `username`?

Every identity always has the field `id` which is used to match a login attempt to existing identities in the database. Some identities also have a `username`. Imagine that you change your GitHub username. You will still be able to use the same login as before because your `id` hasn't changed, only your username. Either `username` or `id` are used to create an URI, depending on the provider (GitHub uses usernames, ORCID uses the ID).

This reminds me that this data should be updated every time a user uses that account to login, and maybe there should be a button to manually update the data.

**Comment by stefandesu** [comment]
Since I already explained `id` and just added removal of the `username` field if it's empty, I think we can close this issue.
